name: Run Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  unit-tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/179131920588/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'ganglia-uploader@halloween2023.iam.gserviceaccount.com'

    - name: Make run_tests.sh executable
      run: chmod +x run_tests.sh
    
    - name: Run unit tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
        GCP_PROJECT_NAME: ${{ secrets.GCP_PROJECT_NAME }}
        SUNO_API_KEY: ${{ secrets.SUNO_API_KEY }}
      run: ./run_tests.sh docker unit

  smoke-tests:
    needs: unit-tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/179131920588/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'ganglia-uploader@halloween2023.iam.gserviceaccount.com'

    - name: Make run_tests.sh executable
      run: chmod +x run_tests.sh
    
    - name: Run smoke tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
        GCP_PROJECT_NAME: ${{ secrets.GCP_PROJECT_NAME }}
        SUNO_API_KEY: ${{ secrets.SUNO_API_KEY }}
      run: ./run_tests.sh docker smoke

  integration-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/179131920588/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'ganglia-uploader@halloween2023.iam.gserviceaccount.com'

    - name: Make run_tests.sh executable
      run: chmod +x run_tests.sh
    
    - name: Run integration tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
        GCP_PROJECT_NAME: ${{ secrets.GCP_PROJECT_NAME }}
        SUNO_API_KEY: ${{ secrets.SUNO_API_KEY }}
      run: ./run_tests.sh docker integration

